apiVersion: apps/v1
kind: Deployment
metadata:
  name: webapp-deployment
  labels:
    app: webapp
spec:
  replicas: 3
  selector:
    matchLabels:
      app: webapp
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate    
  template:
    metadata:
      labels:
        app: webapp
    spec:
      containers:
      - name: front-end
        image: anjurose/udacity-webapp:latest
        ports:
        - containerPort: 5000
